In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
from numpy import *

In [2]:
train = pd.read_csv('train.csv', encoding='latin-1')
test = pd.read_csv('test.csv', encoding='latin-1')

In [3]:
train

ItemID  Sentiment                                      SentimentText
0           1          0                       is so sad for my APL frie...
1           2          0                     I missed the New Moon trail...
2           3          1                            omg its already 7:30 :O
3           4          0            .. Omgaga. Im sooo  im gunna CRy. I'...
4           5          0           i think mi bf is cheating on me!!!   ...
5           6          0                  or i just worry too much?        
6           7          1                 Juuuuuuuuuuuuuuuuussssst Chillin!!
7           8          0         Sunny Again        Work Tomorrow  :-|  ...
8           9          1        handed in my uniform today . i miss you ...
9          10          1           hmmmm.... i wonder how she my number @-)
10         11          0                      I must think about positive..
11         12          1        thanks to all the haters up in my face a...
12         13          0                     this weekend has sucked so far
13         14          0             jb isnt showing in australia any more!
14         15          0                               ok thats it you win.
15         16          0      &lt;-------- This is the way i feel right ...
16         17          0      awhhe man.... I'm completely useless rt no...
17         18          1      Feeling strangely fine. Now I'm gonna go l...
18         19          0       HUGE roll of thunder just now...SO scary!!!!
19         20          0      I just cut my beard off. It's only been gr...
20         21          0                               Very sad about Iran.
21         22          0                                      wompppp wompp
22         23          1      You're the only one who can see this cause...
23         24          0     &lt;---Sad level is 3. I was writing a mass...
24         25          0     ...  Headed to Hospitol : Had to pull out o...
25         26          0     BoRinG   ): whats wrong with him??     Plea...
26         27          0     can't be bothered. i wish i could spend the...
27         28          0     Feeeling like shit right now. I really want...
28         29          1              goodbye exams, HELLO ALCOHOL TONIGHT 
29         30          0     I didn't realize it was THAT deep. Geez giv...
...       ...        ...                                                ...
99959   99971          0  @CT415 @UCLA_Bruin  it made me sad too!  that ...
99960   99972          1  @CT415 I agree. I think they all have that fet...
99961   99973          0  @ct415 I hope it's not too serious of an injur...
99962   99974          0  @ctabita if it's any consolation, this weekend...
99963   99975          1                        @ctayah got your back, yo! 
99964   99976          1  @ctaylor0127 I can't wait to see that movie. E...
99965   99977          1  @ctaylor10127 @smelby I am excited and a littl...
99966   99978          0  @ctb1221 yeah  sorry.going to a concert that n...
99967   99979          1  @ctcash @buildingateam @diabetescure @chocolat...
99968   99980          1  @ctdesign87 im so glad you went to china town ...
99969   99981          0                                 @CTerry1985  Sorry
99970   99982          0                @CTerry1985 damn it, dont have sky 
99971   99983          0  @CTerry1985 That's the thing; the new raft of ...
99972   99984          1                                          @cthagod 
99973   99985          1                              @ctham  #FollowFriday
99974   99986          0  @ctham #awaresg You are not wrong. But from a ...
99975   99987          0  @ctham @mommyfizz cuz you big burly man.  haha...
99976   99988          1  @ctham @Wilsurn Trying to get a wider range of...
99977   99989          1    @ctham Haha I love the passion in your support 
99978   99990          1  @cthulhullahoop That sucks...I like living in ...
99979   99991          1  @cunningstunts till i can go 

In [4]:
train.drop("ItemID",axis=1)

Sentiment                                      SentimentText
0              0                       is so sad for my APL frie...
1              0                     I missed the New Moon trail...
2              1                            omg its already 7:30 :O
3              0            .. Omgaga. Im sooo  im gunna CRy. I'...
4              0           i think mi bf is cheating on me!!!   ...
5              0                  or i just worry too much?        
6              1                 Juuuuuuuuuuuuuuuuussssst Chillin!!
7              0         Sunny Again        Work Tomorrow  :-|  ...
8              1        handed in my uniform today . i miss you ...
9              1           hmmmm.... i wonder how she my number @-)
10             0                      I must think about positive..
11             1        thanks to all the haters up in my face a...
12             0                     this weekend has sucked so far
13             0             jb isnt showing in australia any more!
14             0                               ok thats it you win.
15             0      &lt;-------- This is the way i feel right ...
16             0      awhhe man.... I'm completely useless rt no...
17             1      Feeling strangely fine. Now I'm gonna go l...
18             0       HUGE roll of thunder just now...SO scary!!!!
19             0      I just cut my beard off. It's only been gr...
20             0                               Very sad about Iran.
21             0                                      wompppp wompp
22             1      You're the only one who can see this cause...
23             0     &lt;---Sad level is 3. I was writing a mass...
24             0     ...  Headed to Hospitol : Had to pull out o...
25             0     BoRinG   ): whats wrong with him??     Plea...
26             0     can't be bothered. i wish i could spend the...
27             0     Feeeling like shit right now. I really want...
28             1              goodbye exams, HELLO ALCOHOL TONIGHT 
29             0     I didn't realize it was THAT deep. Geez giv...
...          ...                                                ...
99959          0  @CT415 @UCLA_Bruin  it made me sad too!  that ...
99960          1  @CT415 I agree. I think they all have that fet...
99961          0  @ct415 I hope it's not too serious of an injur...
99962          0  @ctabita if it's any consolation, this weekend...
99963          1                        @ctayah got your back, yo! 
99964          1  @ctaylor0127 I can't wait to see that movie. E...
99965          1  @ctaylor10127 @smelby I am excited and a littl...
99966          0  @ctb1221 yeah  sorry.going to a concert that n...
99967          1  @ctcash @buildingateam @diabetescure @chocolat...
99968          1  @ctdesign87 im so glad you went to china town ...
99969          0                                 @CTerry1985  Sorry
99970          0                @CTerry1985 damn it, dont have sky 
99971          0  @CTerry1985 That's the thing; the new raft of ...
99972          1                                          @cthagod 
99973          1                              @ctham  #FollowFriday
99974          0  @ctham #awaresg You are not wrong. But from a ...
99975          0  @ctham @mommyfizz cuz you big burly man.  haha...
99976          1  @ctham @Wilsurn Trying to get a wider range of...
99977          1    @ctham Haha I love the passion in your support 
99978          1  @cthulhullahoop That sucks...I like living in ...
99979          1  @cunningstunts till i can go home been here ti...
99980          1         @cunningstunts22 afternoon jim hows you  x
99981          0  @cup_a_tea The foot is really bad. Like the wo...
99982          1  @Cup_Of_Katy Have fun doing health &amp; safet...
99983          0  @cupati It took me waaay too long to get your ...
99984          0  @Cupcake  seems like a repeating problem   hop...
99985          1  @cupcake__ arrrr we both replied to each othe

In [5]:
x = train["SentimentText"]

In [6]:
# data has contains number+string so using regular expression removing intigers
import re
patt = re.compile(r'[a-z]*\s+',re.I)
u = list(map(lambda s:''.join(patt.findall(s)),x[:21000]))    
u = list(map(lambda s:s.strip(),u))                         # removing space from front and last
u

['is so sad for my APL',
 'I missed the New Moon',
 'omg its already',
 'Im sooo  im gunna  ve been at this dentist since  I was suposed  just get a crown put on',
 'i think mi bf is cheating on',
 'or i just worry too',
 'Juuuuuuuuuuuuuuuuussssst',
 'Sunny Again        Work Tomorrow         TV',
 'handed in my uniform today  i miss you',
 'i wonder how she my number',
 'I must think about',
 'thanks to all the haters up in my face all',
 'this weekend has sucked so',
 'jb isnt showing in australia any',
 'ok thats it you',
 'This is the way i feel right',
 'awhhe  m completely useless rt   all I can do is',
 'Feeling strangely  Now m gonna go listen to some Semisonic to',
 'HUGE roll of thunder just SO',
 'I just cut my beard  s only been growing for well over a  m gonna start it  shaunamanu is happy in the',
 'Very sad about',
 'wompppp',
 're the only one who can see this cause no one else is following me this is for you because re pretty',
 'Sad level is  I was writing a massive bl

In [7]:
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 
import nltk
nltk.download('stopwords')  
nltk.download('punkt')
stop_words = set(stopwords.words('english')) 

#removing stop word using natural language tool kit nltk
arr = []
for m in u:
    word_tokens = word_tokenize(m) 

    arr.append(" ".join([w for w in word_tokens if not w in stop_words] ))
    
# removing repeat word which have repeat char in string
final_arr = []
for string in arr:
    for word in string.split(" "):
        if len(re.findall(r"((\w)\2{2,})",word)) != 0:
           
            string = string.replace(word,"")
    final_arr.append(string)

 

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Aayush\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Aayush\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [8]:
# removing empty string in list
final_arr = list(filter(None, final_arr) )
final_arr

['sad APL',
 'I missed New Moon',
 'omg already',
 'Im  im gunna dentist since I suposed get crown put',
 'think mi bf cheating',
 'worry',
 'Sunny Again Work Tomorrow TV',
 'handed uniform today miss',
 'wonder number',
 'I must think',
 'thanks haters face',
 'weekend sucked',
 'jb isnt showing australia',
 'ok thats',
 'This way feel right',
 'awhhe completely useless rt I',
 'Feeling strangely Now gon na go listen Semisonic',
 'HUGE roll thunder SO',
 'I cut beard growing well gon na start shaunamanu happy',
 'Very sad',
 'one see cause one else following pretty',
 'Sad level I writing massive blog tweet Myspace comp shut Now lost lays fetal',
 'Headed Hospitol Had pull Golf Tourny rd I Think I Ripped something Yeah THAT',
 'BoRinG whats wrong Please tell',
 'wish could spend rest life sat going',
 ' like shit right I really want  I hours dancing art assignment',
 'goodbye HELLO ALCOHOL TONIGHT',
 'I realize THAT Geez give girl warning',
 'I hate athlete appears tear ACL live',
 'm

In [9]:
# encoding string to train machine learning model.
feature_extra = TfidfVectorizer()
feature_extra.fit(arr)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [10]:
feature_extra.vocabulary_

{'sad': 16192,
 'apl': 870,
 'missed': 12225,
 'new': 12969,
 'moon': 12444,
 'omg': 13477,
 'already': 548,
 'im': 9077,
 'sooo': 17470,
 'gunna': 8013,
 'dentist': 4830,
 'since': 17066,
 'suposed': 18307,
 'get': 7466,
 'crown': 4270,
 'put': 15043,
 'think': 18976,
 'mi': 12043,
 'bf': 1833,
 'cheating': 3232,
 'worry': 21247,
 'juuuuuuuuuuuuuuuuussssst': 10062,
 'sunny': 18280,
 'again': 304,
 'work': 21221,
 'tomorrow': 19287,
 'tv': 19699,
 'handed': 8142,
 'uniform': 20035,
 'today': 19236,
 'miss': 12222,
 'wonder': 21171,
 'number': 13274,
 'must': 12689,
 'thanks': 18844,
 'haters': 8259,
 'face': 6325,
 'weekend': 20781,
 'sucked': 18195,
 'jb': 9687,
 'isnt': 9482,
 'showing': 16951,
 'australia': 1200,
 'ok': 13441,
 'thats': 18858,
 'this': 18994,
 'way': 20704,
 'feel': 6543,
 'right': 15848,
 'awhhe': 1260,
 'completely': 3813,
 'useless': 20173,
 'rt': 16098,
 'feeling': 6547,
 'strangely': 18053,
 'now': 13234,
 'gon': 7698,
 'na': 12753,
 'go': 7650,
 'listen': 1102

In [11]:
feature_extra.get_feature_names()

['aaa',
 'aaaaaaaaa',
 'aaaaaakkkh',
 'aaaaaand',
 'aaaaawwwwwww',
 'aaaahhhh',
 'aaaand',
 'aaah',
 'aaahahaha',
 'aaahhhhhh',
 'aaalisson',
 'aaarrrrrrrrr',
 'aaaw',
 'aachen',
 'aah',
 'aahhh',
 'aahhhh',
 'aalinakirche',
 'aaliyah',
 'aamaustin',
 'aanestad',
 'aar',
 'aaroncarl',
 'aaronrenfree',
 'aaronxnow',
 'aaronyonda',
 'aarrgh',
 'aaw',
 'aawww',
 'aay',
 'ab',
 'abandoning',
 'abb',
 'abba',
 'abbey',
 'abby',
 'abbycowley',
 'abbyy',
 'abc',
 'abd',
 'abdominal',
 'abduct',
 'abducted',
 'abduzeedo',
 'aber',
 'aberdeen',
 'aberonline',
 'abfahrt',
 'abheet',
 'abhl',
 'abhors',
 'abi',
 'abigale',
 'ability',
 'abit',
 'able',
 'abnormal',
 'abnormals',
 'abomination',
 'aboot',
 'abort',
 'abortion',
 'abortions',
 'abortiontuesday',
 'about',
 'above',
 'abraham',
 'abroad',
 'abrupt',
 'abruptly',
 'abs',
 'abseloutly',
 'absence',
 'absent',
 'absoloutely',
 'absolute',
 'absolutely',
 'absolves',
 'absolvo',
 'abstraction',
 'absurd',
 'abt',
 'abuse',
 'abusing',
 

In [12]:
feature_extra.idf_

array([ 9.56603097, 10.25917815, 10.25917815, ..., 10.25917815,
       10.25917815, 10.25917815])

In [13]:
l = feature_extra.transform(arr).toarray() 
l

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import r2_score

In [15]:
# training Logistic Regression machine learning model
y = train["Sentiment"]
model = LogisticRegression()
model.fit(l[:20000],y[:20000])

C:\Users\Aayush\Anaconda3\envs\ml_envs\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [16]:
model.intercept_

array([-0.01666323])

In [17]:
model.coef_

array([[ 0.02549359,  0.18089767, -0.15399178, ...,  0.13839424,
        -0.12290987,  0.19142627]])

In [22]:
prediction = model.predict(l[20000:21000])
r2_score(prediction,y[20000:21000])

-0.28484848484848424

In [23]:
t  = feature_extra.transform(["hii this is not good"])
model.predict(t.toarray())

array([0], dtype=int64)