In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("USA_Housing.csv")

In [4]:
data.columns

Index(['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population', 'Price', 'Address'],
      dtype='object')

In [5]:
data

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0         79545.458574             5.682861                   7.009188   
1         79248.642455             6.002900                   6.730821   
2         61287.067179             5.865890                   8.512727   
3         63345.240046             7.188236                   5.586729   
4         59982.197226             5.040555                   7.839388   
5         80175.754159             4.988408                   6.104512   
6         64698.463428             6.025336                   8.147760   
7         78394.339278             6.989780                   6.620478   
8         59927.660813             5.362126                   6.393121   
9         81885.927184             4.423672                   8.167688   
10        80527.472083             8.093513                   5.042747   
11        50593.695497             4.496513                   7.467627   
12        39033.809237             7.671755                   7.250029   
13        73163.663441             6.919535                   5.993188   
14        69391.380184             5.344776                   8.406418   
15        73091.866746             5.443156                   8.517513   
16        79706.963058             5.067890                   8.219771   
17        61929.077018             4.788550                   5.097010   
18        63508.194299             5.947165                   7.187774   
19        62085.276403             5.739411                   7.091808   
20        86294.999089             6.627457                   8.011898   
21        60835.089979             5.551222                   6.517175   
22        64490.650267             4.210323                   5.478088   
23        60697.351539             6.170484                   7.150537   
24        59748.855487             5.339340                   7.748682   
25        56974.476539             8.287562                   7.312880   
26        82173.626076             4.018525                   6.992699   
27        64626.880978             5.443360                   6.988754   
28        90499.057451             6.384359                   4.242191   
29        59323.792100             6.977828                   8.273697   
...                ...                  ...                        ...   
4970      55980.204807             7.014510                   5.458789   
4971      73491.134427             5.784430                   4.425959   
4972      83695.272383             7.643507                   7.127219   
4973      78743.759274             6.583685                   6.595683   
4974      70720.296463             6.411801                   5.048128   
4975      54037.580879             8.471765                   6.966072   
4976      75046.313791             5.351169                   7.797825   
4977      75980.438843             6.583105                   5.914892   
4978      80393.339500             8.899713                   5.652974   
4979      82224.695006             5.434087                   8.375708   
4980      75664.024482             5.789203                   6.415312   
4981      71663.871293             6.150745                   7.311907   
4982      58800.908770             5.976507                   7.304051   
4983      69655.183954             7.721100                   6.077795   
4984      62623.359828             5.071624                   6.771015   
4985      75117.042949             6.036275                   6.538111   
4986      71060.406015             5.718839                   7.222730   
4987      65729.222330             6.237787                   6.860475   
4988      67637.840665             7.056673                   5.774409   
4989      47965.406896             5.694638                   7.363327   
4990      52723.876555             5.452237                   8.124571   
4991      74102.191890             5.657841                   7.683993   
4992      

In [6]:
x = data[['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population']].values
x

array([[7.95454586e+04, 5.68286132e+00, 7.00918814e+00, 4.09000000e+00,
        2.30868005e+04],
       [7.92486425e+04, 6.00289981e+00, 6.73082102e+00, 3.09000000e+00,
        4.01730722e+04],
       [6.12870672e+04, 5.86588984e+00, 8.51272743e+00, 5.13000000e+00,
        3.68821594e+04],
       ...,
       [6.33906869e+04, 7.25059061e+00, 4.80508098e+00, 2.13000000e+00,
        3.32661455e+04],
       [6.80013312e+04, 5.53438842e+00, 7.13014386e+00, 5.44000000e+00,
        4.26256202e+04],
       [6.55105818e+04, 5.99230531e+00, 6.79233610e+00, 4.07000000e+00,
        4.65012838e+04]])

In [7]:
y = data['Price'].values
y

array([1059033.55787012, 1505890.91484695, 1058987.98787608, ...,
       1030729.58315229, 1198656.87240769, 1298950.48026696])

In [8]:
def eulidean_Distance(old_x,new_x,y,k):
    distance = list([np.sqrt(sum((new_x[col]-old_x[row,col])**2 for col in range(old_x.shape[1]))),y[row]]for row in range(old_x.shape[0]))
    distance = sorted(distance,key= lambda x:x[0])
    return np.array(distance[:k])
    

In [14]:
new =[7.95454586e+04, 5.68286132e+00, 7.00918814e+00, 4.09000000e+00,2.30868005e+04]
min_k_distance = eulidean_Distance(x,new,y,3)
min_k_distance


array([[2.58233327e-05, 1.05903356e+06],
       [4.73279384e+02, 1.61740542e+06],
       [5.31774719e+02, 1.08401378e+06]])

In [15]:
prediction = np.mean(min_k_distance[:,1])      # we take mean of top k nearest value in our case k = 3
prediction

1253484.2558366423